In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [77]:
jr = pd.read_csv("hiring.csv")

In [78]:
jr

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [79]:
jr["test_score(out of 10)"] = jr["test_score(out of 10)"].fillna(jr["test_score(out of 10)"].median())


In [94]:
jr.replace(to_replace = ("five","two","seven","three","ten","eleven") ,value = (5,2,7,3,10,11) ,inplace = True)

In [98]:
jr["experience"]= jr["experience"].fillna(5)
jr

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          5                    8.0                           9      50000
1          5                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    8.0                           7      72000
7         11                    7.0                           8      80000

In [99]:
y = jr["salary($)"]
x = jr.drop("salary($)", axis= "columns")

In [103]:
jr

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          5                    8.0                           9      50000
1          5                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    8.0                           7      72000
7         11                    7.0                           8      80000

In [100]:
lin = linear_model.LinearRegression()
lin.fit(x,y)

LinearRegression()

In [101]:
lin.intercept_

5918.063888238721

In [102]:
lin.coef_

array([3221.39134934, 1617.86554643, 3176.24086827])

In [104]:
lin.predict([[2,9,6]])

array([45979.08171436])

In [105]:
lin.predict([[12,10,10]])

array([92515.82422727])

In [107]:
lin.score(x,y)

0.5650729068403858