In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [5]:
iris = load_iris()

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [23]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, y_train,cv=3)


array([0.94285714, 0.91428571, 0.94285714])

In [8]:
cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [11]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.98])

In [17]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.94])

In [19]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
dtc.score(X_test,y_test)

0.9333333333333333

In [ ]:
**Best score so far is from SVM: 0.98**